### ISSUE TITLE
[MednaNetAPI] Parse certain discord text formatting

### ISSUE THREAD

**Issue by Asnivor** [Asnivor/MednaNet#5]
* multiline (returning \n delimited string perhaps)
* strange blockquote-looking text generated by webhooks (again returning as \n delimited string)

**Comment by SteveBurgess** [comment]
Test comment

**Comment by SteveBurgess** [comment]
Another test comment

**Comment by SteveBurgess** [comment]
Another test comment

**Comment by SteveBurgess** [comment]
Test comment

**Comment by SteveBurgess** [comment]
Test comment

**Comment by SteveBurgess** [comment]
Test Comment

**Comment by SteveBurgess** [comment]
Test Comment

**Comment by SteveBurgess** [comment]
Test comment

**Comment by SteveBurgess** [comment]
Test comment

**Comment by SteveBurgess** [comment]
Test comment

**Comment by SteveBurgess** [comment]
Test comment

**Comment by SteveBurgess** [comment]
This has been implemented now.
