### ISSUE TITLE
[MednaNetAPI] Client receives ?? in the message body in place of unicode chars

### ISSUE THREAD

**Issue by Asnivor** [Asnivor/MednaNet#7]

**Comment by Asnivor** [comment]
![image](https://user-images.githubusercontent.com/7911038/30745831-871db5c8-9f9f-11e7-92ec-3e4601bef223.png)

**Comment by SteveBurgess** [comment]
![image](https://user-images.githubusercontent.com/4759608/30773678-2af30ed2-a06d-11e7-84f0-39532ca9b723.png)

Unicode characters are coming through correctly now for the message body.
