### ISSUE TITLE
[MednaNetAPI] client.Channels.CreateMessage() returns a null user object

### ISSUE THREAD

**Issue by Asnivor** [Asnivor/MednaNet#9]
... and a null instantiated DateTime postedOn value:

![image](https://user-images.githubusercontent.com/7911038/30802434-76574218-a1de-11e7-8d80-606693e2c004.png)

Using latest MednaNetAPIClient appveyor build.

Ideally this should return a valid user object so that client can deal with the message locally and not have to wait for the next GetMessages() poll.

**Comment by SteveBurgess** [comment]
CreateMessage now returns the correct message object including all the correct properties.
